//! Phase 7 build.rs codegen: walk the upstream `NodeType::is_secret_bearing()`
//! and `SlotSubkey::is_secret_bearing()` impls to generate
//! `$OUT_DIR/secrets_generated.rs` containing two `pub const &[&str]` arrays
//! used by the GUI's secret-handling code at runtime.
//!
//! Upstream-source resolution (SPEC §B.11, R3 C-1 + R4 I-1 folds):
//!   1. `MNEMONIC_GUI_UPSTREAM_ROOT` env var.
//!   2. `[upstream].checkout-root` field in `pinned-upstream.toml`.
//!   3. `target/upstream/<tag>/` shallow auto-clone — ONLY when
//!      `MNEMONIC_GUI_ALLOW_UPSTREAM_CLONE=1` is set (opt-in).
//!   4. Stub fallback: emit empty arrays + `cargo:warning=`.
//!
//! Failure modes:
//!   - Upstream tree unresolvable → stub fallback (Phase 0-6 tests pass;
//!     Phase 7's source-audit tests fail with a clear message).
//!   - Variant in `is_secret_bearing()` true-arm but missing from
//!     `as_str()` arm set → `panic!()` (R4 C-1 fold: this is the load-
//!     bearing failure primitive; `cargo:warning=` alone would silently
//!     corrupt SECRET_* arrays).

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use syn::{File, Ident, Item};

const STUB_WARNING: &str =
    "mnemonic-gui: upstream source not available; SECRET_* constants are STUB. \
     Set MNEMONIC_GUI_UPSTREAM_ROOT, or MNEMONIC_GUI_ALLOW_UPSTREAM_CLONE=1, \
     or populate target/upstream/ manually, to enable the source-level audit.";

fn main() {
    println!("cargo:rerun-if-changed=pinned-upstream.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=MNEMONIC_GUI_UPSTREAM_ROOT");
    println!("cargo:rerun-if-env-changed=MNEMONIC_GUI_ALLOW_UPSTREAM_CLONE");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_file = out_dir.join("secrets_generated.rs");

    let pinned = match parse_pinned_upstream() {
        Some(p) => p,
        None => {
            write_stub(&out_file);
            return;
        }
    };

    let upstream_root = match resolve_upstream_root(&pinned) {
        Some(p) => p,
        None => {
            write_stub(&out_file);
            return;
        }
    };

    let mnemonic_member = &pinned.mnemonic.workspace_member_path;
    let convert_path = upstream_root
        .join(mnemonic_member)
        .join("src/cmd/convert.rs");
    let slot_input_path = upstream_root
        .join(mnemonic_member)
        .join("src/slot_input.rs");

    if !convert_path.is_file() || !slot_input_path.is_file() {
        println!(
            "cargo:warning=mnemonic-gui: upstream files not found at {:?} / {:?} — falling back to stub.",
            convert_path, slot_input_path
        );
        write_stub(&out_file);
        return;
    }

    // R1 C-1 fold: register the resolved upstream source files as rerun
    // triggers. Without this, a developer who edits convert.rs or
    // slot_input.rs in their local MNEMONIC_GUI_UPSTREAM_ROOT checkout
    // would NOT trigger build.rs to regenerate secrets_generated.rs;
    // cargo build would silently ship stale SECRET_* constants.
    println!("cargo:rerun-if-changed={}", convert_path.display());
    println!("cargo:rerun-if-changed={}", slot_input_path.display());

    let secret_nodes =
        extract_secret_variants(&convert_path, "NodeType").expect("extract NodeType");
    let secret_subkeys =
        extract_secret_variants(&slot_input_path, "SlotSubkey").expect("extract SlotSubkey");

    let body = format!(
        r#"// Generated by build.rs from upstream {convert_p:?} + {slot_p:?}.
// Do not edit; regenerated on every build when the upstream source
// changes. SPEC §10 R1 I-4 + Phase 7 R2 C-1 fold.

pub const SECRET_NODE_TYPES: &[&str] = &[
{nodes}];

pub const SECRET_SLOT_SUBKEYS: &[&str] = &[
{subkeys}];
"#,
        convert_p = convert_path,
        slot_p = slot_input_path,
        nodes = format_arr(&secret_nodes),
        subkeys = format_arr(&secret_subkeys),
    );
    fs::write(&out_file, body).expect("write secrets_generated.rs");
}

fn format_arr(tokens: &[String]) -> String {
    let mut s = String::new();
    for t in tokens {
        s.push_str("    \"");
        s.push_str(t);
        s.push_str("\",\n");
    }
    s
}

#[derive(Debug)]
struct PinnedUpstream {
    checkout_root: Option<String>,
    mnemonic: PinnedRepo,
}

#[derive(Debug)]
struct PinnedRepo {
    tag: String,
    url: String,
    workspace_member_path: String,
}

fn parse_pinned_upstream() -> Option<PinnedUpstream> {
    let p = Path::new(env!("CARGO_MANIFEST_DIR")).join("pinned-upstream.toml");
    let raw = fs::read_to_string(&p).ok()?;
    let parsed: toml::Value = toml::from_str(&raw).ok()?;

    let checkout_root = parsed
        .get("upstream")
        .and_then(|v| v.get("checkout-root"))
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string());

    let mnemonic = parsed.get("mnemonic")?;
    Some(PinnedUpstream {
        checkout_root,
        mnemonic: PinnedRepo {
            tag: mnemonic.get("tag")?.as_str()?.to_string(),
            url: mnemonic.get("url")?.as_str()?.to_string(),
            workspace_member_path: mnemonic
                .get("workspace-member-path")?
                .as_str()?
                .to_string(),
        },
    })
}

fn resolve_upstream_root(pinned: &PinnedUpstream) -> Option<PathBuf> {
    // Step 1: env var.
    if let Some(p) = env::var_os("MNEMONIC_GUI_UPSTREAM_ROOT") {
        let pb = PathBuf::from(p);
        if pb.is_dir() {
            return Some(pb);
        }
    }
    // Step 2: toml field.
    if let Some(rel) = &pinned.checkout_root {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let resolved = if Path::new(rel).is_absolute() {
            PathBuf::from(rel)
        } else {
            manifest_dir.join(rel)
        };
        if resolved.is_dir() {
            return Some(resolved);
        }
    }
    // Step 3: auto-clone (opt-in only).
    if env::var_os("MNEMONIC_GUI_ALLOW_UPSTREAM_CLONE").as_deref() == Some(std::ffi::OsStr::new("1"))
    {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let target_dir = manifest_dir
            .join("target/upstream")
            .join(&pinned.mnemonic.tag);
        if !target_dir.is_dir() {
            let status = std::process::Command::new("git")
                .args([
                    "clone",
                    "--depth",
                    "1",
                    "--branch",
                    &pinned.mnemonic.tag,
                    &pinned.mnemonic.url,
                    target_dir.to_str().unwrap(),
                ])
                .status();
            if matches!(status, Ok(s) if s.success()) {
                return Some(target_dir);
            }
        } else {
            return Some(target_dir);
        }
    }
    // Step 4: stub fallback.
    None
}

fn write_stub(out_file: &Path) {
    println!("cargo:warning={}", STUB_WARNING);
    let body = format!(
        "// Stub fallback — upstream source unresolvable. {}\n\
         pub const SECRET_NODE_TYPES: &[&str] = &[];\n\
         pub const SECRET_SLOT_SUBKEYS: &[&str] = &[];\n",
        STUB_WARNING
    );
    fs::write(out_file, body).expect("write stub secrets_generated.rs");
}

/// Walk a `src/cmd/convert.rs`-style file for the given target type
/// (`NodeType` or `SlotSubkey`), extract the variants the
/// `is_secret_bearing()` method returns `true` for, and normalize them
/// via the matching `as_str()` impl.
fn extract_secret_variants(file_path: &Path, target_type: &str) -> Option<Vec<String>> {
    let src = fs::read_to_string(file_path).ok()?;
    let parsed: File = syn::parse_file(&src).ok()?;

    // Find the impl block for `target_type`.
    let mut secret_variants: Vec<Ident> = Vec::new();
    let mut as_str_map: Vec<(Ident, String)> = Vec::new();

    for item in &parsed.items {
        if let Item::Impl(imp) = item {
            // Only consider impl blocks with NO trait (inherent impls).
            if imp.trait_.is_some() {
                continue;
            }
            let self_ty_str = quote_to_string(&imp.self_ty);
            if self_ty_str != target_type {
                continue;
            }
            for method in &imp.items {
                if let syn::ImplItem::Fn(f) = method {
                    let name = f.sig.ident.to_string();
                    if name == "is_secret_bearing" {
                        secret_variants = extract_true_match_arms(&f.block, target_type);
                    } else if name == "as_str" {
                        as_str_map = extract_as_str_map(&f.block, target_type);
                    }
                }
            }
        }
    }

    let mut out = Vec::new();
    for variant in &secret_variants {
        let v_str = variant.to_string();
        let mapped = as_str_map
            .iter()
            .find(|(id, _)| id == variant)
            .map(|(_, s)| s.clone())
            .unwrap_or_else(|| {
                // R4 C-1: load-bearing panic. cargo:warning= alone would
                // silently corrupt SECRET_* arrays.
                println!(
                    "cargo:warning=mnemonic-gui: build.rs cannot map variant {} ...",
                    v_str
                );
                panic!(
                    "mnemonic-gui: build.rs cannot map variant {} to its as_str() form; \
                     the upstream impl deviates from the expected literal match self {{ \
                     Variant => \"...\", ... }} shape. File issue at \
                     https://github.com/bg002h/mnemonic-gui",
                    v_str
                );
            });
        out.push(mapped);
    }
    Some(out)
}

/// Pretty-print a `syn::Type` to a string (e.g., `NodeType` → "NodeType").
fn quote_to_string<T: quote::ToTokens>(t: &T) -> String {
    let mut s = String::new();
    for tok in t.to_token_stream() {
        s.push_str(&tok.to_string());
    }
    s
}

/// Given an `is_secret_bearing` method body, extract the variant
/// identifiers it returns `true` for. Handles two shapes:
///   (a) `matches!(self, Pattern1 | Pattern2 | ...)` — variants in the
///       pattern alt list.
///   (b) `match self { Pattern1 | Pattern2 => true, _ => false }` —
///       variants on the `true` arm's pattern.
fn extract_true_match_arms(block: &syn::Block, target_type: &str) -> Vec<Ident> {
    use syn::{Expr, Pat, Stmt};
    let mut out = Vec::new();

    for stmt in &block.stmts {
        // Inspect both bare-expression-as-last-statement AND macro-as-last-
        // statement (Stmt::Macro variant for tail-position macro calls).
        let macro_call: Option<&syn::Macro> = match stmt {
            Stmt::Expr(Expr::Macro(m), _) => Some(&m.mac),
            Stmt::Macro(sm) => Some(&sm.mac),
            _ => None,
        };
        if let Some(mac) = macro_call {
            if mac
                .path
                .segments
                .last()
                .map(|s| s.ident == "matches")
                .unwrap_or(false)
            {
                let toks_str = mac.tokens.to_string();
                if let Some(comma_idx) = toks_str.find(',') {
                    let pat_str = toks_str[comma_idx + 1..].trim();
                    // `matches!` accepts `|`-separated patterns. Use
                    // `parse_multi_with_leading_vert` (returns a Pat::Or
                    // for multi-alt) which correctly handles both single
                    // patterns and or-patterns.
                    if let Ok(pat) = syn::parse::Parser::parse_str(
                        Pat::parse_multi_with_leading_vert,
                        pat_str,
                    ) {
                        collect_variants_from_pat(&pat, target_type, &mut out);
                    }
                }
                continue;
            }
        }
        if let Stmt::Expr(Expr::Match(m), _) = stmt {
            for arm in &m.arms {
                if let Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Bool(b),
                    ..
                }) = &*arm.body
                {
                    if b.value() {
                        collect_variants_from_pat(&arm.pat, target_type, &mut out);
                    }
                }
            }
        }
    }
    out
}

/// Walk a `Pat` and collect every variant identifier of `target_type`.
fn collect_variants_from_pat(pat: &syn::Pat, target_type: &str, out: &mut Vec<Ident>) {
    use syn::Pat;
    match pat {
        Pat::Or(or_pat) => {
            for p in &or_pat.cases {
                collect_variants_from_pat(p, target_type, out);
            }
        }
        Pat::Path(path_pat) => {
            // e.g., `NodeType::Phrase` or `Self::Phrase`.
            if let Some(variant) = extract_variant_ident(&path_pat.path, target_type) {
                if !out.iter().any(|i| i == &variant) {
                    out.push(variant);
                }
            }
        }
        Pat::TupleStruct(ts) => {
            // e.g., `NodeType::Phrase(_)` — variant with inner.
            if let Some(variant) = extract_variant_ident(&ts.path, target_type) {
                if !out.iter().any(|i| i == &variant) {
                    out.push(variant);
                }
            }
        }
        _ => {}
    }
}

fn extract_variant_ident(path: &syn::Path, target_type: &str) -> Option<Ident> {
    let segs: Vec<_> = path.segments.iter().map(|s| s.ident.to_string()).collect();
    // Two recognized shapes:
    //   target_type::Variant   (segs.len() == 2, segs[0] == target_type)
    //   Self::Variant          (segs.len() == 2, segs[0] == "Self")
    if segs.len() == 2 && (segs[0] == target_type || segs[0] == "Self") {
        Some(path.segments.last().unwrap().ident.clone())
    } else {
        None
    }
}

/// Given an `as_str` method body of shape `match self { V => "v", ... }`,
/// extract the (variant_ident, string_literal) pairs.
fn extract_as_str_map(block: &syn::Block, target_type: &str) -> Vec<(Ident, String)> {
    use syn::{Expr, Stmt};
    let mut out = Vec::new();
    for stmt in &block.stmts {
        let m = match stmt {
            Stmt::Expr(Expr::Match(m), _) => m,
            _ => continue,
        };
        for arm in &m.arms {
            let lit = match &*arm.body {
                Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(s),
                    ..
                }) => s.value(),
                _ => continue,
            };
            let mut variants: Vec<Ident> = Vec::new();
            collect_variants_from_pat(&arm.pat, target_type, &mut variants);
            for v in variants {
                out.push((v, lit.clone()));
            }
        }
    }
    out
}
