//! Schema-mirror invariant test (SPEC §11).
//!
//! For each (CLI, subcommand) listed in the in-process `Schema`, shell out
//! to `<cli> <subcommand> --help`, regex-extract every `--<flag-name>`
//! token, and assert set-equality with the schema's flag-name set
//! (excluding the auto-injected `--help`).
//!
//! Binary lookup: `<CLI_uppercase>_BIN` env var (e.g. `MNEMONIC_BIN`) wins;
//! otherwise the literal binary name is invoked through `$PATH`.

use std::collections::BTreeSet;
use std::process::Command;

use mnemonic_gui::schema;

/// Extract every `--[a-z][a-z0-9-]+` token from `text`. Mirrors the
/// `grep -oE -- '--[a-z][a-z0-9-]+'` extractor used by
/// `mnemonic-toolkit/docs/manual/tests/lint.sh` (SPEC §11 prior-art).
fn extract_flag_names(text: &str) -> BTreeSet<String> {
    let bytes = text.as_bytes();
    let mut out = BTreeSet::new();
    let mut i = 0;
    while i + 2 < bytes.len() {
        if bytes[i] == b'-' && bytes[i + 1] == b'-' && bytes[i + 2].is_ascii_lowercase() {
            let start = i;
            i += 2;
            while i < bytes.len()
                && (bytes[i].is_ascii_lowercase() || bytes[i].is_ascii_digit() || bytes[i] == b'-')
            {
                i += 1;
            }
            let name = std::str::from_utf8(&bytes[start..i]).unwrap().to_string();
            // Defensive: trailing `--` (from `cargo test -- ...`) would
            // produce an empty name; the byte test above filters it.
            if name.len() > 2 {
                out.insert(name);
            }
        } else {
            i += 1;
        }
    }
    out
}

/// Resolve the binary name. `MNEMONIC_BIN` etc. override $PATH.
fn resolve_bin(cli_name: &str) -> String {
    let env_var = format!("{}_BIN", cli_name.to_ascii_uppercase().replace('-', "_"));
    std::env::var(&env_var).unwrap_or_else(|_| cli_name.to_string())
}

fn schema_flag_names(sub: &schema::SubcommandSchema) -> BTreeSet<String> {
    sub.flags.iter().map(|f| f.name.to_string()).collect()
}

fn help_text_flag_names(bin: &str, subcommand: &str) -> BTreeSet<String> {
    let output = Command::new(bin)
        .args([subcommand, "--help"])
        .output()
        .unwrap_or_else(|e| {
            panic!(
                "failed to spawn `{} {} --help`: {} (set {}_BIN env var to override $PATH lookup)",
                bin,
                subcommand,
                e,
                bin.to_ascii_uppercase().replace('-', "_")
            )
        });
    // Some sibling CLIs (ms-cli, mk-cli) exit non-zero even on --help due
    // to a sysexits-style main wrapper (FOLLOWUPS candidate: convince
    // upstream to use clap's default `ExitCode::SUCCESS` for --help).
    // Stdout still carries the help text correctly, so we don't require
    // a zero exit code — only that stdout is non-empty.
    let text = if !output.stdout.is_empty() {
        String::from_utf8(output.stdout).expect("help-text stdout must be UTF-8")
    } else {
        panic!(
            "`{} {} --help` produced empty stdout (exit {:?})\nstderr:\n{}",
            bin,
            subcommand,
            output.status.code(),
            String::from_utf8_lossy(&output.stderr)
        );
    };
    let mut names = extract_flag_names(&text);
    // clap auto-injects `--help`; the schema deliberately omits it.
    names.remove("--help");
    names
}

fn assert_schema_matches_help(schema: &schema::Schema) {
    let bin = resolve_bin(schema.cli_name);
    for sub in schema.subcommands {
        let from_schema = schema_flag_names(sub);
        let from_help = help_text_flag_names(&bin, sub.name);
        let only_in_schema: Vec<_> = from_schema.difference(&from_help).collect();
        let only_in_help: Vec<_> = from_help.difference(&from_schema).collect();
        assert!(
            only_in_schema.is_empty() && only_in_help.is_empty(),
            "schema-mirror drift for `{} {}`:\n  only in schema: {:?}\n  only in upstream --help: {:?}",
            schema.cli_name,
            sub.name,
            only_in_schema,
            only_in_help,
        );
    }
}

#[test]
fn mnemonic_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::mnemonic::SCHEMA);
}

#[test]
fn md_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::md::SCHEMA);
}

#[test]
fn ms_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::ms::SCHEMA);
}

#[test]
fn mk_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::mk::SCHEMA);
}

// ── Phase 7 source-level audit: SECRET_* arrays vs upstream source ─────
//
// The arrays in `mnemonic_gui::secrets` are GENERATED by `build.rs` from
// upstream source. These cells re-do the syn walk at TEST time and assert
// set-equality. Drift between upstream and generated constants surfaces
// here. The mutation cell (`source_audit_detects_mutation`) verifies the
// audit actually CATCHES drift by pointing it at a synthetic minimal
// fixture whose `is_secret_bearing` arm-set differs.

mod source_audit {
    use std::collections::BTreeSet;
    use std::path::{Path, PathBuf};

    use mnemonic_gui::secrets::{SECRET_NODE_TYPES, SECRET_SLOT_SUBKEYS};

    fn upstream_root() -> PathBuf {
        std::env::var("MNEMONIC_GUI_UPSTREAM_ROOT")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from("/scratch/code/shibboleth/mnemonic-toolkit"))
    }

    /// Re-parse `file_path` for `target_type` and return the variant
    /// `as_str()` form for every variant the `is_secret_bearing()`
    /// method returns `true` for. Mirrors build.rs but in test code so
    /// we don't double-count its bugs.
    pub fn parse_secret_set(file_path: &Path, target_type: &str) -> BTreeSet<String> {
        let src = std::fs::read_to_string(file_path)
            .unwrap_or_else(|e| panic!("read {:?}: {}", file_path, e));
        let parsed = syn::parse_file(&src).expect("syn::parse_file");

        let mut variants: Vec<syn::Ident> = Vec::new();
        let mut as_str_map: Vec<(syn::Ident, String)> = Vec::new();

        for item in &parsed.items {
            if let syn::Item::Impl(imp) = item {
                if imp.trait_.is_some() {
                    continue;
                }
                let self_ty = quote::ToTokens::to_token_stream(&*imp.self_ty).to_string();
                if self_ty != target_type {
                    continue;
                }
                for m in &imp.items {
                    if let syn::ImplItem::Fn(f) = m {
                        if f.sig.ident == "is_secret_bearing" {
                            variants = extract_secret_variants_from_block(&f.block);
                        } else if f.sig.ident == "as_str" {
                            as_str_map = extract_as_str_map_from_block(&f.block);
                        }
                    }
                }
            }
        }

        variants
            .into_iter()
            .filter_map(|v| {
                as_str_map
                    .iter()
                    .find(|(id, _)| id == &v)
                    .map(|(_, s)| s.clone())
            })
            .collect()
    }

    fn extract_secret_variants_from_block(block: &syn::Block) -> Vec<syn::Ident> {
        use syn::{Expr, Pat, Stmt};
        let mut out: Vec<syn::Ident> = Vec::new();
        for stmt in &block.stmts {
            let mac: Option<&syn::Macro> = match stmt {
                Stmt::Expr(Expr::Macro(em), _) => Some(&em.mac),
                Stmt::Macro(sm) => Some(&sm.mac),
                _ => None,
            };
            if let Some(m) = mac {
                if m.path.segments.last().map(|s| s.ident == "matches").unwrap_or(false) {
                    let toks = m.tokens.to_string();
                    if let Some(idx) = toks.find(',') {
                        let pat_str = toks[idx + 1..].trim();
                        if let Ok(pat) = syn::parse::Parser::parse_str(
                            Pat::parse_multi_with_leading_vert,
                            pat_str,
                        ) {
                            collect_variants(&pat, &mut out);
                        }
                    }
                    continue;
                }
            }
            if let Stmt::Expr(Expr::Match(m), _) = stmt {
                for arm in &m.arms {
                    if let Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Bool(b),
                        ..
                    }) = &*arm.body
                    {
                        if b.value() {
                            collect_variants(&arm.pat, &mut out);
                        }
                    }
                }
            }
        }
        out
    }

    fn extract_as_str_map_from_block(block: &syn::Block) -> Vec<(syn::Ident, String)> {
        use syn::{Expr, Stmt};
        let mut out = Vec::new();
        for stmt in &block.stmts {
            let Stmt::Expr(Expr::Match(m), _) = stmt else {
                continue;
            };
            for arm in &m.arms {
                let lit = match &*arm.body {
                    Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Str(s),
                        ..
                    }) => s.value(),
                    _ => continue,
                };
                let mut vs: Vec<syn::Ident> = Vec::new();
                collect_variants(&arm.pat, &mut vs);
                for v in vs {
                    out.push((v, lit.clone()));
                }
            }
        }
        out
    }

    fn collect_variants(pat: &syn::Pat, out: &mut Vec<syn::Ident>) {
        use syn::Pat;
        match pat {
            Pat::Or(or_pat) => {
                for p in &or_pat.cases {
                    collect_variants(p, out);
                }
            }
            Pat::Path(pp) => {
                if let Some(last) = pp.path.segments.last() {
                    if !out.iter().any(|i| i == &last.ident) {
                        out.push(last.ident.clone());
                    }
                }
            }
            Pat::TupleStruct(ts) => {
                if let Some(last) = ts.path.segments.last() {
                    if !out.iter().any(|i| i == &last.ident) {
                        out.push(last.ident.clone());
                    }
                }
            }
            _ => {}
        }
    }

    #[test]
    fn source_audit_secret_node_types_matches_generated() {
        let path = upstream_root().join("crates/mnemonic-toolkit/src/cmd/convert.rs");
        let from_source = parse_secret_set(&path, "NodeType");
        let generated: BTreeSet<String> = SECRET_NODE_TYPES.iter().map(|s| s.to_string()).collect();
        if generated.is_empty() {
            panic!(
                "SECRET_NODE_TYPES is empty — build.rs ran in stub-fallback mode. \
                 Set MNEMONIC_GUI_UPSTREAM_ROOT to a local mnemonic-toolkit checkout \
                 and rebuild."
            );
        }
        assert_eq!(
            from_source, generated,
            "build.rs-generated SECRET_NODE_TYPES drifts from upstream NodeType::is_secret_bearing()"
        );
    }

    #[test]
    fn source_audit_secret_slot_subkeys_matches_generated() {
        let path = upstream_root().join("crates/mnemonic-toolkit/src/slot_input.rs");
        let from_source = parse_secret_set(&path, "SlotSubkey");
        let generated: BTreeSet<String> = SECRET_SLOT_SUBKEYS.iter().map(|s| s.to_string()).collect();
        if generated.is_empty() {
            panic!(
                "SECRET_SLOT_SUBKEYS is empty — build.rs ran in stub-fallback mode."
            );
        }
        assert_eq!(
            from_source, generated,
            "build.rs-generated SECRET_SLOT_SUBKEYS drifts from upstream SlotSubkey::is_secret_bearing()"
        );
    }

    #[test]
    fn source_audit_detects_mutation() {
        // R3 I-1 + R4 I-2 fold: synthetic fixture intentionally OMITS
        // `Phrase` from is_secret_bearing(). The audit must detect this
        // as set-inequality vs the generated SECRET_NODE_TYPES.
        let fixture = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/mutated_convert.rs");
        let from_fixture = parse_secret_set(&fixture, "NodeType");
        let generated: BTreeSet<String> = SECRET_NODE_TYPES.iter().map(|s| s.to_string()).collect();
        assert_ne!(
            from_fixture, generated,
            "mutation fixture (Phrase omitted) must NOT match the upstream-generated set"
        );
        // Specifically: phrase is in generated but not in fixture.
        assert!(
            generated.contains("phrase"),
            "generated set should contain 'phrase'"
        );
        assert!(
            !from_fixture.contains("phrase"),
            "fixture should NOT contain 'phrase' (intentional mutation)"
        );
    }
}

#[test]
fn extract_flag_names_handles_basic_help_text() {
    let sample = "Options:\n  --network <NETWORK>  [possible values: mainnet]\n  --template <T>\n  -h, --help\n";
    let names = extract_flag_names(sample);
    assert!(names.contains("--network"));
    assert!(names.contains("--template"));
    assert!(names.contains("--help"));
    // Negative: dashes alone, single-dash short opts, uppercase starts.
    assert!(!names.contains("--"));
    assert!(!names.contains("--NETWORK"));
}
