//! Schema-mirror invariant test (SPEC §11).
//!
//! For each (CLI, subcommand) listed in the in-process `Schema`, shell out
//! to `<cli> <subcommand> --help`, regex-extract every `--<flag-name>`
//! token, and assert set-equality with the schema's flag-name set
//! (excluding the auto-injected `--help`).
//!
//! Binary lookup: `<CLI_uppercase>_BIN` env var (e.g. `MNEMONIC_BIN`) wins;
//! otherwise the literal binary name is invoked through `$PATH`.

use std::collections::BTreeSet;
use std::process::Command;

use mnemonic_gui::schema;

/// Extract every `--[a-z][a-z0-9-]+` token from `text`. Mirrors the
/// `grep -oE -- '--[a-z][a-z0-9-]+'` extractor used by
/// `mnemonic-toolkit/docs/manual/tests/lint.sh` (SPEC §11 prior-art).
fn extract_flag_names(text: &str) -> BTreeSet<String> {
    let bytes = text.as_bytes();
    let mut out = BTreeSet::new();
    let mut i = 0;
    while i + 2 < bytes.len() {
        if bytes[i] == b'-' && bytes[i + 1] == b'-' && bytes[i + 2].is_ascii_lowercase() {
            let start = i;
            i += 2;
            while i < bytes.len()
                && (bytes[i].is_ascii_lowercase() || bytes[i].is_ascii_digit() || bytes[i] == b'-')
            {
                i += 1;
            }
            let name = std::str::from_utf8(&bytes[start..i]).unwrap().to_string();
            // Defensive: trailing `--` (from `cargo test -- ...`) would
            // produce an empty name; the byte test above filters it.
            if name.len() > 2 {
                out.insert(name);
            }
        } else {
            i += 1;
        }
    }
    out
}

/// Resolve the binary name. `MNEMONIC_BIN` etc. override $PATH.
fn resolve_bin(cli_name: &str) -> String {
    let env_var = format!("{}_BIN", cli_name.to_ascii_uppercase().replace('-', "_"));
    std::env::var(&env_var).unwrap_or_else(|_| cli_name.to_string())
}

fn schema_flag_names(sub: &schema::SubcommandSchema) -> BTreeSet<String> {
    sub.flags.iter().map(|f| f.name.to_string()).collect()
}

fn help_text_flag_names(bin: &str, subcommand: &str) -> BTreeSet<String> {
    let output = Command::new(bin)
        .args([subcommand, "--help"])
        .output()
        .unwrap_or_else(|e| {
            panic!(
                "failed to spawn `{} {} --help`: {} (set {}_BIN env var to override $PATH lookup)",
                bin,
                subcommand,
                e,
                bin.to_ascii_uppercase().replace('-', "_")
            )
        });
    // Some sibling CLIs (ms-cli, mk-cli) exit non-zero even on --help due
    // to a sysexits-style main wrapper (FOLLOWUPS candidate: convince
    // upstream to use clap's default `ExitCode::SUCCESS` for --help).
    // Stdout still carries the help text correctly, so we don't require
    // a zero exit code — only that stdout is non-empty.
    let text = if !output.stdout.is_empty() {
        String::from_utf8(output.stdout).expect("help-text stdout must be UTF-8")
    } else {
        panic!(
            "`{} {} --help` produced empty stdout (exit {:?})\nstderr:\n{}",
            bin,
            subcommand,
            output.status.code(),
            String::from_utf8_lossy(&output.stderr)
        );
    };
    let mut names = extract_flag_names(&text);
    // clap auto-injects `--help`; the schema deliberately omits it.
    names.remove("--help");
    names
}

fn assert_schema_matches_help(schema: &schema::Schema) {
    let bin = resolve_bin(schema.cli_name);
    for sub in schema.subcommands {
        let from_schema = schema_flag_names(sub);
        let from_help = help_text_flag_names(&bin, sub.name);
        let only_in_schema: Vec<_> = from_schema.difference(&from_help).collect();
        let only_in_help: Vec<_> = from_help.difference(&from_schema).collect();
        assert!(
            only_in_schema.is_empty() && only_in_help.is_empty(),
            "schema-mirror drift for `{} {}`:\n  only in schema: {:?}\n  only in upstream --help: {:?}",
            schema.cli_name,
            sub.name,
            only_in_schema,
            only_in_help,
        );
    }
}

#[test]
fn mnemonic_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::mnemonic::SCHEMA);
}

#[test]
fn md_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::md::SCHEMA);
}

#[test]
fn ms_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::ms::SCHEMA);
}

#[test]
fn mk_schema_flag_names_match_help_text() {
    assert_schema_matches_help(&schema::mk::SCHEMA);
}

// ── Phase 7 source-level audit: SECRET_* arrays vs upstream source ─────
//
// The arrays in `mnemonic_gui::secrets` are GENERATED by `build.rs` from
// upstream source. These cells re-do the syn walk at TEST time and assert
// set-equality. Drift between upstream and generated constants surfaces
// here. The mutation cell (`source_audit_detects_mutation`) verifies the
// audit actually CATCHES drift by pointing it at a synthetic minimal
// fixture whose `is_secret_bearing` arm-set differs.

mod source_audit {
    use std::collections::BTreeSet;
    use std::path::{Path, PathBuf};

    use mnemonic_gui::secrets::{SECRET_NODE_TYPES, SECRET_SLOT_SUBKEYS};

    fn upstream_root() -> PathBuf {
        std::env::var("MNEMONIC_GUI_UPSTREAM_ROOT")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from("/scratch/code/shibboleth/mnemonic-toolkit"))
    }

    /// Re-parse `file_path` for `target_type` and return the variant
    /// `as_str()` form for every variant the `is_secret_bearing()`
    /// method returns `true` for. Mirrors build.rs but in test code so
    /// we don't double-count its bugs.
    pub fn parse_secret_set(file_path: &Path, target_type: &str) -> BTreeSet<String> {
        let src = std::fs::read_to_string(file_path)
            .unwrap_or_else(|e| panic!("read {:?}: {}", file_path, e));
        let parsed = syn::parse_file(&src).expect("syn::parse_file");

        let mut variants: Vec<syn::Ident> = Vec::new();
        let mut as_str_map: Vec<(syn::Ident, String)> = Vec::new();

        for item in &parsed.items {
            if let syn::Item::Impl(imp) = item {
                if imp.trait_.is_some() {
                    continue;
                }
                let self_ty = quote::ToTokens::to_token_stream(&*imp.self_ty).to_string();
                if self_ty != target_type {
                    continue;
                }
                for m in &imp.items {
                    if let syn::ImplItem::Fn(f) = m {
                        if f.sig.ident == "is_secret_bearing" {
                            variants =
                                extract_secret_variants_from_block_with_type(&f.block, target_type);
                        } else if f.sig.ident == "as_str" {
                            as_str_map =
                                extract_as_str_map_from_block_with_type(&f.block, target_type);
                        }
                    }
                }
            }
        }

        variants
            .into_iter()
            .filter_map(|v| {
                as_str_map
                    .iter()
                    .find(|(id, _)| id == &v)
                    .map(|(_, s)| s.clone())
            })
            .collect()
    }

    /// R1 I-1 fold: thread target_type through to mirror build.rs's
    /// two-segment guard (Self::Variant or target_type::Variant only).
    fn extract_secret_variants_from_block_with_type(
        block: &syn::Block,
        target_type: &str,
    ) -> Vec<syn::Ident> {
        extract_secret_variants_from_block_filtered(block, |path: &syn::Path| {
            two_segment_guard(path, target_type)
        })
    }

    fn two_segment_guard(path: &syn::Path, target_type: &str) -> bool {
        let segs: Vec<_> = path.segments.iter().map(|s| s.ident.to_string()).collect();
        segs.len() == 2 && (segs[0] == target_type || segs[0] == "Self")
    }

    fn extract_secret_variants_from_block_filtered(
        block: &syn::Block,
        accept: impl Fn(&syn::Path) -> bool + Copy,
    ) -> Vec<syn::Ident> {
        use syn::{Expr, Pat, Stmt};
        let mut out: Vec<syn::Ident> = Vec::new();
        for stmt in &block.stmts {
            let mac: Option<&syn::Macro> = match stmt {
                Stmt::Expr(Expr::Macro(em), _) => Some(&em.mac),
                Stmt::Macro(sm) => Some(&sm.mac),
                _ => None,
            };
            if let Some(m) = mac {
                if m.path.segments.last().map(|s| s.ident == "matches").unwrap_or(false) {
                    let toks = m.tokens.to_string();
                    if let Some(idx) = toks.find(',') {
                        let pat_str = toks[idx + 1..].trim();
                        if let Ok(pat) = syn::parse::Parser::parse_str(
                            Pat::parse_multi_with_leading_vert,
                            pat_str,
                        ) {
                            collect_variants_filtered(&pat, accept, &mut out);
                        }
                    }
                    continue;
                }
            }
            if let Stmt::Expr(Expr::Match(m), _) = stmt {
                for arm in &m.arms {
                    if let Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Bool(b),
                        ..
                    }) = &*arm.body
                    {
                        if b.value() {
                            collect_variants_filtered(&arm.pat, accept, &mut out);
                        }
                    }
                }
            }
        }
        out
    }

    fn extract_as_str_map_from_block_with_type(
        block: &syn::Block,
        target_type: &str,
    ) -> Vec<(syn::Ident, String)> {
        use syn::{Expr, Stmt};
        let mut out = Vec::new();
        for stmt in &block.stmts {
            let Stmt::Expr(Expr::Match(m), _) = stmt else {
                continue;
            };
            for arm in &m.arms {
                let lit = match &*arm.body {
                    Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Str(s),
                        ..
                    }) => s.value(),
                    _ => continue,
                };
                let mut vs: Vec<syn::Ident> = Vec::new();
                collect_variants_filtered(
                    &arm.pat,
                    |p: &syn::Path| two_segment_guard(p, target_type),
                    &mut vs,
                );
                for v in vs {
                    out.push((v, lit.clone()));
                }
            }
        }
        out
    }

    /// R1 I-1 fold: filter-aware variant collector. Mirrors
    /// `build.rs::extract_variant_ident`'s two-segment guard so the
    /// test-side audit accepts exactly the same patterns build.rs does.
    fn collect_variants_filtered(
        pat: &syn::Pat,
        accept: impl Fn(&syn::Path) -> bool + Copy,
        out: &mut Vec<syn::Ident>,
    ) {
        use syn::Pat;
        match pat {
            Pat::Or(or_pat) => {
                for p in &or_pat.cases {
                    collect_variants_filtered(p, accept, out);
                }
            }
            Pat::Path(pp)
                if accept(&pp.path) => {
                    if let Some(last) = pp.path.segments.last() {
                        if !out.iter().any(|i| i == &last.ident) {
                            out.push(last.ident.clone());
                        }
                    }
                }
            Pat::TupleStruct(ts)
                if accept(&ts.path) => {
                    if let Some(last) = ts.path.segments.last() {
                        if !out.iter().any(|i| i == &last.ident) {
                            out.push(last.ident.clone());
                        }
                    }
                }
            _ => {}
        }
    }

    #[test]
    fn source_audit_secret_node_types_matches_generated() {
        let path = upstream_root().join("crates/mnemonic-toolkit/src/cmd/convert.rs");
        let from_source = parse_secret_set(&path, "NodeType");
        let generated: BTreeSet<String> = SECRET_NODE_TYPES.iter().map(|s| s.to_string()).collect();
        if generated.is_empty() {
            panic!(
                "SECRET_NODE_TYPES is empty — build.rs ran in stub-fallback mode. \
                 Set MNEMONIC_GUI_UPSTREAM_ROOT to a local mnemonic-toolkit checkout \
                 and rebuild."
            );
        }
        assert_eq!(
            from_source, generated,
            "build.rs-generated SECRET_NODE_TYPES drifts from upstream NodeType::is_secret_bearing()"
        );
    }

    #[test]
    fn source_audit_secret_slot_subkeys_matches_generated() {
        let path = upstream_root().join("crates/mnemonic-toolkit/src/slot_input.rs");
        let from_source = parse_secret_set(&path, "SlotSubkey");
        let generated: BTreeSet<String> = SECRET_SLOT_SUBKEYS.iter().map(|s| s.to_string()).collect();
        if generated.is_empty() {
            panic!(
                "SECRET_SLOT_SUBKEYS is empty — build.rs ran in stub-fallback mode."
            );
        }
        assert_eq!(
            from_source, generated,
            "build.rs-generated SECRET_SLOT_SUBKEYS drifts from upstream SlotSubkey::is_secret_bearing()"
        );
    }

    #[test]
    fn source_audit_detects_mutation() {
        // R3 I-1 + R4 I-2 fold: synthetic fixture intentionally OMITS
        // `Phrase` from is_secret_bearing(). The audit must detect this
        // as set-inequality vs the generated SECRET_NODE_TYPES.
        let fixture = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/mutated_convert.rs");
        let from_fixture = parse_secret_set(&fixture, "NodeType");
        let generated: BTreeSet<String> = SECRET_NODE_TYPES.iter().map(|s| s.to_string()).collect();
        assert_ne!(
            from_fixture, generated,
            "mutation fixture (Phrase omitted) must NOT match the upstream-generated set"
        );
        // Specifically: phrase is in generated but not in fixture.
        assert!(
            generated.contains("phrase"),
            "generated set should contain 'phrase'"
        );
        assert!(
            !from_fixture.contains("phrase"),
            "fixture should NOT contain 'phrase' (intentional mutation)"
        );
    }
}

// ── Phase 9: CI workflow snapshot regression guard ─────────────────────
//
// Phase 9 IMPL_PLAN: tests/schema_mirror.rs::ci_workflow_snapshot reads
// .github/workflows/schema-mirror.yml and asserts the YAML's required
// step names are present. Authored AFTER the workflow YAML is on disk
// (post-implementation snapshot, NOT RED-driver) — guards against
// accidental workflow regression (e.g., future maintainer dropping the
// clone-upstream step).

#[test]
fn ci_workflow_snapshot() {
    let workflow_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(".github/workflows/schema-mirror.yml");
    let body = std::fs::read_to_string(&workflow_path)
        .unwrap_or_else(|e| panic!("read {:?}: {}", workflow_path, e));

    // Required step names (substring assertion — simpler + more
    // diff-resistant than full YAML parsing).
    let required_steps = [
        "install-mnemonic-toolkit",
        "install-md-cli",
        "install-ms-cli",
        "install-mk-cli",
        "clone-upstream-mnemonic-toolkit",
        "cargo-test-schema-mirror",
        // Phase C.3 v0.2: per-CLI gui-schema smoke steps assert that
        // each installed binary exposes a SPEC §7 `gui-schema` subcommand
        // emitting `{version:1, cli:<name>, ...}`. If the smoke step is
        // dropped the CI gate stops noticing a regression at the
        // subcommand boundary even when the rest of the workflow
        // passes.
        "smoke-gui-schema-mnemonic",
        "smoke-gui-schema-md",
        "smoke-gui-schema-ms",
        "smoke-gui-schema-mk",
    ];
    for step in &required_steps {
        assert!(
            body.contains(step),
            "schema-mirror.yml must contain step `{}`",
            step
        );
    }

    // Required pinned tags — the workflow installs the binaries that
    // tests/schema_mirror.rs cells run against. If the pin drifts
    // here without the schema also drifting, the CI gate fails.
    //
    // Phase C.3 v0.2: bumped in lockstep with the sibling-repo
    // `gui-schema` PRs that landed at C.2. Each bump corresponds to a
    // release tag that includes the new subcommand.
    let required_tags = [
        "mnemonic-toolkit-v0.9.0",
        "descriptor-mnemonic-md-cli-v0.5.0",
        "ms-cli-v0.2.1",
        "mk-cli-v0.3.1",
    ];
    for tag in &required_tags {
        assert!(
            body.contains(tag),
            "schema-mirror.yml must pin tag `{}`",
            tag
        );
    }

    // MNEMONIC_GUI_UPSTREAM_ROOT must be set before running the
    // schema_mirror test so build.rs resolves upstream from the temp
    // clone (not the stub fallback).
    assert!(
        body.contains("MNEMONIC_GUI_UPSTREAM_ROOT"),
        "schema-mirror.yml must set MNEMONIC_GUI_UPSTREAM_ROOT env var"
    );
}

// ── Phase A.1 (v0.2): doubled-prefix artifact fix snapshot ─────────────
//
// SPEC §9 / Phase A.1: build.yml computes a `VERSION` env var by
// stripping the `mnemonic-gui-` prefix from `github.ref_name`, and
// templates artifact filenames against `${{ env.VERSION }}`. Pre-fix,
// the workflow templated against `${{ env.REF_NAME }}` (raw ref name),
// producing doubled-prefix artifacts like
// `mnemonic-gui-mnemonic-gui-v0.1.0-x86_64-linux.tar.gz`. This cell
// pins the fix: future edits that drop `compute-version` or reintroduce
// `env.REF_NAME` in any artifact-name template fail this snapshot.
//
// Authored AFTER the workflow YAML is on disk (post-implementation
// snapshot, NOT RED-driver) — Phase A.1 declared a RED-test exception
// because CI YAML correctness is not reachable from `cargo test`.

#[test]
fn ci_build_version_step_present() {
    let workflow_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(".github/workflows/build.yml");
    let body = std::fs::read_to_string(&workflow_path)
        .unwrap_or_else(|e| panic!("read {:?}: {}", workflow_path, e));

    // Required: a `compute-version` step exists and uses `shell: bash`
    // (Windows runners default to PowerShell; bash makes the strip
    // portable across all five matrix targets).
    assert!(
        body.contains("name: compute-version"),
        "build.yml must contain a `compute-version` step that strips \
         the `mnemonic-gui-` prefix from github.ref_name into a \
         `VERSION` env var (Phase A.1 / SPEC §9)"
    );
    assert!(
        body.contains("shell: bash"),
        "build.yml `compute-version` step must declare `shell: bash` \
         so the prefix-strip parameter expansion works on the Windows \
         runner (PowerShell default would break it)"
    );

    // Forbidden: any GitHub Actions template expression accessing the
    // raw `env.REF_NAME` value (which carries the doubled prefix).
    // Artifact-name templates must use `env.VERSION` instead.
    assert!(
        !body.contains("env.REF_NAME"),
        "build.yml must not reference `env.REF_NAME` — that's the \
         pre-Phase-A.1 raw ref name that produced doubled-prefix \
         artifacts. Use `env.VERSION` (computed by the \
         `compute-version` step) in artifact-name templates."
    );

    // Required (Phase E follow-up to Phase A.1): the compute-version
    // step must sanitize slashes in the stripped VERSION. PR refs
    // are `<N>/merge` (head merge-ref); interpolating that raw into
    // `mnemonic-gui-${VERSION}-<suffix>.tar.gz` makes tar/7z try to
    // create a path with a directory separator in the basename and
    // fail with "Failed to open". The fix replaces `/` with `-` so
    // any ref (PR or tag) yields a single-segment filename. The
    // exact bash form `${VERSION//\//-}` is searched for here so a
    // future maintainer accidentally dropping the sanitize fails the
    // snapshot rather than the macOS package step.
    assert!(
        body.contains("${VERSION//\\//-}"),
        "build.yml `compute-version` step must sanitize slashes in \
         VERSION via the bash `${{VERSION//\\//-}}` form. PR refs \
         like `1/merge` would otherwise break tar/7z when \
         interpolated into the artifact filename."
    );

    // Required: artifact-name templates use `env.VERSION`. Four sites
    // mirror the four template locations in build.yml: `package-unix`
    // ARTIFACT, `package-windows` ARTIFACT, `upload-artifact` name,
    // `upload-artifact` path.
    let env_version_count = body.matches("env.VERSION").count();
    assert_eq!(
        env_version_count, 4,
        "build.yml must reference `env.VERSION` exactly 4 times (one \
         each for package-unix ARTIFACT, package-windows ARTIFACT, \
         upload-artifact name, upload-artifact path) — found {}",
        env_version_count
    );
}

// ── Phase C.1 (v0.2): `--gui-schema` JSON consumer ─────────────────────

#[test]
fn schema_check_json_parse_returns_flag_names() {
    use mnemonic_gui::schema_check::parse_gui_schema_json;
    // SPEC §7 sample: minimal JSON with one subcommand + one flag.
    let json = r#"{
        "version": 1,
        "cli": "md",
        "subcommands": [
            {
                "name": "encode",
                "flags": [
                    { "name": "--output", "required": false, "kind": "path", "choices": null }
                ],
                "positionals": []
            }
        ]
    }"#;
    let names = parse_gui_schema_json(json, "encode")
        .expect("encode subcommand present + version 1");
    assert!(names.contains("--output"));
}

#[test]
fn schema_check_json_rejects_non_version_1() {
    use mnemonic_gui::schema_check::parse_gui_schema_json;
    // SPEC §7: GUI rejects non-1 versions and falls back to regex path.
    let json = r#"{"version":2,"cli":"md","subcommands":[]}"#;
    assert!(parse_gui_schema_json(json, "encode").is_none());
}

#[test]
fn schema_check_json_returns_none_for_missing_subcommand() {
    use mnemonic_gui::schema_check::parse_gui_schema_json;
    let json = r#"{"version":1,"cli":"md","subcommands":[{"name":"decode","flags":[]}]}"#;
    assert!(parse_gui_schema_json(json, "encode").is_none());
}

#[test]
fn schema_check_json_invokes_gui_schema_on_capable_cli() {
    // Phase C.3 v0.2: all four CLIs are now `gui-schema-capable = true`
    // in pinned-upstream.toml, in lockstep with the bumped tags
    // (mnemonic-toolkit-v0.9.0 / md-v0.5.0 / ms-v0.2.0 / mk-v0.3.0).
    // `json_flag_names` should exec the installed binary's
    // `gui-schema` subcommand and return `Some(...)` for an existing
    // subcommand.
    //
    // The binary lookup matches schema_check.rs::json_flag_names: it
    // honours the per-CLI *_BIN env var (set by CI), falling back to
    // bare-name PATH lookup. Skip the cell if a binary cannot be
    // located so dev-laptop runs without the sibling CLIs installed
    // don't spuriously fail.
    for (cli, sub) in [
        ("mnemonic", "bundle"),
        ("md", "encode"),
        ("ms", "encode"),
        ("mk", "encode"),
    ] {
        let env_var = format!("{}_BIN", cli.to_uppercase());
        let candidate = std::env::var(&env_var).ok().unwrap_or_else(|| cli.to_string());
        let probe = std::process::Command::new(&candidate)
            .arg("gui-schema")
            .output();
        match probe {
            Ok(o) if o.status.success() => {}
            Ok(o) => {
                eprintln!(
                    "skipping {cli}: gui-schema exited {:?} stderr={}",
                    o.status,
                    String::from_utf8_lossy(&o.stderr)
                );
                continue;
            }
            Err(e) => {
                eprintln!("skipping {cli}: cannot exec {candidate:?}: {e}");
                continue;
            }
        }
        let result = mnemonic_gui::schema_check::json_flag_names(cli, sub);
        assert!(
            result.is_some(),
            "gui-schema-capable=true expects Some(_) for {cli} {sub}; got None"
        );
        assert!(
            !result.as_ref().unwrap().is_empty(),
            "{cli} {sub} should expose at least one flag via gui-schema"
        );
    }
}

#[test]
fn pinned_upstream_gui_schema_capable_all_true_at_c3() {
    // Phase C.3 v0.2 invariant: all four CLI sections carry
    // `gui-schema-capable = true` once the sibling-repo PRs land and
    // the tag pins move forward (which happens together at C.3). If
    // any CLI is still `false` here, either (a) the sibling-repo PR
    // didn't ship the subcommand, or (b) the tag bump was applied
    // without flipping the capability flag — both leave the schema
    // gate stuck on the regex-on-`--help` fallback path.
    let body = std::fs::read_to_string(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("pinned-upstream.toml"),
    )
    .expect("read pinned-upstream.toml");
    let occurrences = body.matches("gui-schema-capable = true").count();
    assert_eq!(
        occurrences, 4,
        "expected 4 'gui-schema-capable = true' occurrences in pinned-upstream.toml; got {}",
        occurrences
    );
    assert!(
        !body.contains("gui-schema-capable = false"),
        "no CLI should be gui-schema-capable = false at Phase C.3"
    );
}

// ── Phase B.2 (v0.2): platform module compile gate ─────────────────────

#[test]
fn platform_module_compiles_linux() {
    // SPEC §4 / Phase B.2 plan line 801: assert the platform module
    // signature is importable and exposes the expected function. The
    // test cannot drive a live WindowHandle in a unit-test context;
    // it asserts the public function type-checks. Linux CI implicitly
    // exercises the cfg-not-any branch; macOS/Windows CI implicitly
    // exercise their cfg-gated branches.
    use raw_window_handle::WindowHandle;
    let f: fn(WindowHandle<'_>) = mnemonic_gui::platform::apply_window_capture_protection;
    // Use `f` so the binding doesn't get dead-code-eliminated. (The
    // function is never invoked here — no live WindowHandle exists.)
    let _ = f;

    // Linux build must not emit any `unsafe` block from this module
    // (cfg-not-any branch is pure tracing::debug). Spot-check via
    // source-substring: there is no `unsafe` token inside the
    // cfg-not-any branch.
    let src = std::fs::read_to_string(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/platform.rs"),
    )
    .expect("read src/platform.rs");
    let linux_branch_start = src
        .find("#[cfg(not(any(target_os = \"macos\", windows)))]")
        .expect("Linux cfg-not-any branch present");
    let linux_branch_end = src[linux_branch_start..]
        .find("\n}")
        .map(|n| linux_branch_start + n)
        .unwrap_or(src.len());
    let linux_branch = &src[linux_branch_start..linux_branch_end];
    assert!(
        !linux_branch.contains("unsafe"),
        "Linux branch of src/platform.rs must contain no `unsafe`"
    );
}

#[test]
fn extract_flag_names_handles_basic_help_text() {
    let sample = "Options:\n  --network <NETWORK>  [possible values: mainnet]\n  --template <T>\n  -h, --help\n";
    let names = extract_flag_names(sample);
    assert!(names.contains("--network"));
    assert!(names.contains("--template"));
    assert!(names.contains("--help"));
    // Negative: dashes alone, single-dash short opts, uppercase starts.
    assert!(!names.contains("--"));
    assert!(!names.contains("--NETWORK"));
}
